development:
  adapter: postgresql
  username: Zangrandi
  password: 4Fokodugue!
  pool: 5
  timeout: 5000
  min_messages: WARNING
  database: pdf_forms_development
  
test:
  adapter: postgresql
  username: Zangrandi
  password: 4Fokodugue!
  pool: 5
  timeout: 5000
  min_messages: WARNING
  database: pdf_forms_test

production:
  adapter: postgresql
  username: Zangrandi
  password: 4Fokodugue!
  pool: 5
  timeout: 5000
  min_messages: WARNING
  database: pdf_forms_production